# Generated by Django 5.0.3 on 2024-03-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
