# Generated by Django 5.0.3 on 2024-03-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_author_slug'),
        ('quotes', '0004_auto_20240311_1153'),
    ]

    operations = [
    ]
